sonar.projectKey=foodxpress-order-service
sonar.organization=asirialwis

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
